# Default values for cluster-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: kube-system
image:
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.30.1 # The Cluster Autoscaler’s version should match the Cluster’s Version (https://github.com/kubernetes/autoscaler/releases)

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations:
    IAM_role_arn: arn:aws:iam::123456789012:role/your-role-name

podAnnotations: {
  prometheus.io/scrape: 'true',
  prometheus.io/port: '8085'
}
podLabels: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 600Mi

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes:
  - name: ssl-certs
    hostPath:
      path: "/etc/ssl/certs/ca-bundle.crt"

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: ssl-certs
    mountPath: /etc/ssl/certs/ca-certificates.crt # /etc/ssl/certs/ca-bundle.crt for Amazon Linux Worker Nodes
    readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
