{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .IAM_role_arn }}
  {{- end }}
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
{{- end }}
